from backend.backendConstants import LABELDATE


DASYTOSHOW = 730
CURRENTDATEFORMAT = "YYYY-MM-DD- ISODate"

LABELHOUR = "Horas:"
LABELDATE = "Dia:"
LABELPLACE = "Local:"
LABELMATTER = "Proc nº:"
LABELSUPPERIOR = "Tribunal:"
LABELNAME = "Nome:"
LABELFINNISHED = "Realizado? :"

#Display Constants
SIZEDIVIDER = 30
NUMBEROFDAYSTOSHOW = 4

#Message Constants
    #WARNING MESSAGES
NOEVENT = "NENHUM EVENTO EXISTENTE"
NOEVENTDATE = "NENHUM EVENTO COM DATA"
DATEERROR = "ERRO NA INTRODUÇÃO DA DATA"
EVENTEXISTS = "JA EXISTE UM EVENTO PARA A DATA E HORA COLOCADA"
ERRORSAVING = "ERRO ENQUANTO TENTAVA SALVAR"
ERRORMESSAGESTITLE = "OCORREU UM ERRO"
DISPLAYREMOVEDEVENT = "REMOVIDO EVENTO DE:"
EVENTDELETED = "EVENTO SELECIONADO FOI PREVIAMENTE APAGADO"

    #INFORMATION MESSAGE
ACTIONOCOURED = "Ação registada"
EVENTINSERTED = "EVENTO INTRODUZIDO COM DATA E HORA :"
EVENTCHANGED = "EVENTO ALTERADO CORRETAMENTE"
SUCCESSSAVE = "AGENDA SALVA CORRETAMENTE"

#Buttons
ADDEVENTS = "Adicionar Eventos"
ADDEVENT = "Adicionar Evento"
DELETEEVENT = "Apagar Evento"
SAVESYSTEM  = "Salvar Agenda"
SEEEDITEVENTS = "Ver/Editar Eventos"
DELETELAST = "Apagar Ultimo Evento Inserido"
DELETEEVENT = "Apagar Evento"
SAVEEVENT = "Salvar Evento"
NEXTEVENT = "Proximo Evento"